name: Run tests

on: [push, pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
    - name: Preparations
      run: |
        make setup
    - name: Redis up
      run: |
        make redis
    - name: Celery up
      run: |
        make worker
    - name: Django up
      run: |
        make server
    - name: Run Tests
      run: |
        python manage.py test
